name: Go Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
      id: go
    - uses: mirromutth/mysql-action@v1
      with:
        mysql database: 'test'
        mysql root password: 'supertest'
        mysql user: 'tester'
        mysql password: 'testerpw'
    - name: Test
      run: go test -v ./...
